apiVersion: v1
kind: Service
metadata:
  labels:
    app: postgres-svc
  name: postgres-svc
spec:
  clusterIP: None
  ports:
  - name: postgres-svc
    port: 5432
    targetPort: 5432
  selector:
    app: postgres
  type: ClusterIP
